name: Release nightly

on:
  push:
    # branches:
    #   - main

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'VOICEVOX'
    steps:
      - name: Trigger workflow_dispatch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const latest_release = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const split_version = latest_release.data.tag_name.split('.');
            const nightly_version = `${split_version[0]}.${parseInt(split_version[1]) + 1}.0-nightly`;

            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                version: nightly_version,
                prerelease: true
              }
            })

            console.log(`Triggered workflow_dispatch for ${nightly_version}`);
